import type { Metadata } from "next";
import { Bebas_Neue, Merienda } from "next/font/google";
import "./globals.css";
import { StarsBackground } from "@/components/animate-ui/components/backgrounds/stars";
import Navber from "@/components/Navber";

const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  subsets: ["latin"],
  weight: "400",
});

const merienda = Merienda({
  variable: "--font-merienda",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${bebasNeue.variable} ${merienda.variable} min-h-screen antialiased`}
    >
      <body className="flex flex-col">
        
          <StarsBackground className="absolute inset-0 z-[-1]" />
       
       
          <Navber />
        {children}
       
      </body>
    </html>
  );
}
